FROM python:3.11.10-slim-bookworm@sha256:5148c0e4bbb64271bca1d3322360ebf4bfb7564507ae32dd639322e4952a6b16

ARG SOURCE_DATE_EPOCH

WORKDIR /app

RUN echo "Create a file" > file.txt

COPY requirements.txt .